name: Audit

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    container: cronoslabs/dev:v1.10.8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install BPF toolchain
        run: |
          rustup default stable
          cd /root/.local/share/solana/install/active_release/bin/sdk/bpf/scripts
          ./install.sh
          cd $HOME
          rustup default bpf
      - name: Audit heartbeat program
        run: |
          cd programs/heartbeat
          soteria -analyzeAll .
          cd ../../
      - name: Audit network program
        run: |
          cd programs/network
          soteria -analyzeAll .
          cd ../../
      - name: Audit scheduler program
        run: |
          cd programs/scheduler
          soteria -analyzeAll .
          cd ../../
