name: Bump version

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'New version'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - rc
          - beta
          - alpha
      extra_args:
        description: 'Extra args to pass to bump-version.sh, e.g: --dry-run.'
        required: false
        default: '--exclude clockwork-thread-program-v1'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: Bump version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: jq

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install cargo-edit
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-edit
          version: "0.11.9"

      - name: Run version bump script
        run: |
          cd ${{ github.workspace }}
          source ./scripts/ci/bump-version.sh ${{ github.event.inputs.bump }} ${{ github.event.inputs.extra_args }}
          echo "OLD_VERSION=$old_version" | tee -a $GITHUB_ENV
          echo "NEW_VERSION=$new_version" | tee -a $GITHUB_ENV
        env:
          RUST_BACKTRACE: full

      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --locked

      - name: Commit and tag
        uses: EndBug/add-and-commit@v9
        with:
          message: Bump from ${{ env.OLD_VERSION }} to ${{ env.NEW_VERSION }}
          tag: v${{ env.NEW_VERSION }}
